#https://helm.sh/docs/chart_template_guide/accessing_files/#lines
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret-cfg
  labels:
    variant: {{ include "app.variant" . }}
    {{- include "app.labels" . | nindent 4 }}
  namespace: {{ include "app.namespace" . }}
type: Opaque
stringData:
{{ range .Files.Lines "files/app-secret.cfg" }}{{ . | indent 2 }}{{ end }}
{{/*data:*/}}
{{/*  {{ (.Files.Glob "files/app-secret.cfg").AsSecrets | indent 2 }}*/}}
{{/*  {{ (.Files.Glob "files/app-secret.cfg").AsConfig | indent 2 }}*/}}
{{/*  token: |-*/}}
{{/*    {{ .Files.Get "files/app-secret.cfg" | indent 2 }}*/}}
