apiVersion: v1
kind: Service
metadata:
    name: app-api
    labels:
        tier: app-api
    namespace: app
spec:
    type: LoadBalancer                # A port is opened on each node in your cluster via Kube proxy.
    ports:
        - port: 3000
          targetPort: 8080
    selector:
        tier: app-api
