apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-net
  namespace: go-app
spec:
  podSelector: {}
  egress:
    - {}
  ingress:
    - {}
  policyTypes:
    - Egress
    - Ingress
