namespace: ""   # if set override .Release.Namespace
variant: ""     # if set override .Release.Name

secretData:
  appPgUser: postgres
  appPgPass: postgres

configData:
  appConfigFile: /app/defcfg/app.global.yaml
  appHttpPort: "8080"
  appHttpListenSpec: 0.0.0.0:8080
  appLogLevel: INFO
  appLogFile: /app/log/app.log
  appPgPort: "5432"
  appPgDbname: postgres
  appPgInstallEmptyChangelog: db.changelog-root.xml
  appPgInstallTestdataChangelog: db.changelog-1.0_testData.xml
#  appPgUpgradeChangelog: db.changelog-1.0_recreate_testdata.xml

appApi:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 90
    targetMemoryUtilizationPercentage: 90
    packetsPerSecond: ""
  resources:
     limits:
       cpu: 1000m
       memory: 2048Mi
     requests:
       cpu: 100m
       memory: 300Mi
  service:
    type: LoadBalancer
    port: 3001

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: localhost
      paths:
        - path: /app-local
          pathType: ImplementationSpecific
  tls: []
